# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.CharField(max_length=100, null=True, unique=True)),
                ('Location', models.CharField(default='', max_length=100, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Power_source', 'Power_source')], max_length=100, null=True)),
            ],
        ),
    ]
