# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_auto_20180704_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='Snmpv3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
