# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_auto_20180704_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='Note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
