# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='DU',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
