# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abnormal',
            old_name='abnor',
            new_name='bkfailed',
        ),
        migrations.RenameField(
            model_name='abnormal',
            old_name='num',
            new_name='nonstandard',
        ),
        migrations.AddField(
            model_name='abnormal',
            name='offline',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
