# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageview', '0002_auto_20180806_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sub_view_count',
        ),
    ]
