# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageview', '0003_remove_page_sub_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='refresh_count',
            field=models.IntegerField(default=0, help_text='refresh_count', null=True),
        ),
    ]
