"""
Django settings for management project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import djcelery

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c+elqzh%sox48__&!2chnhya-^*8a4kpgg^2q66nlii!=g!*$c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
X_FRAME_OPTIONS = 'ALLOW'
CORS_ORIGIN_ALLOW_ALL = True
# Application definition
#python manage.py migrate --database=ddb01
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'switch',
    'brand',
    'data',
    'abnormal',
    'subnet',
    'device',
    'djcelery',
    'department',
    'pageview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASE_APPS_MAPPING = {
    # example:
    # 'app_name':'database_name',

    'data': 'db01',
    'brand':'db02',
    'abnormal':'db03',
    'subnet':'db04',
    'device': 'db05',
    'department': 'db06',
    'pageview':'db07',

}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'switch',
        'HOST':'127.0.0.1',
        'PORT':'3311',
        'USER':'root',
        'PASSWORD':'HZnokia123',
    },
    'db01': {

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'data',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',
    },
    'db02': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'brand',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',
    }
,
    'db03': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'abnormal',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',
    }
,
    'db04': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'subnet',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',
    },

    'db05': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'device',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',
    },
    'db06':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'department',
        'HOST': '127.0.0.1',
        'PORT': '3311',
        'USER': 'root',
        'PASSWORD': 'HZnokia123',

    },
    'db07':{
      'ENGINE': 'django.db.backends.sqlite3',
       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
    
}
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

    }
}'''

DATABASE_ROUTERS = ['management.routers.DatabaseAppsRouter']
#projectname= management
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_NUMBER_FIELDS=2000


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

djcelery.setup_loader()
#BROKER_URL = 'redis://localhost:6379/0'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

UNDOWNLOADABLE_IP = []