# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_auto_20180621_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='Authentication_protocol',
            field=models.CharField(blank=True, choices=[('MD5', 'MD5'), ('SHA', 'SHA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='Authority',
            field=models.CharField(blank=True, choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='privacy_protocol',
            field=models.CharField(blank=True, choices=[('DES', 'DES'), ('AES', 'AES')], max_length=100, null=True),
        ),
    ]
