# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index_count', models.IntegerField(help_text='page_index_count', null=True)),
                ('sub_view_count', models.IntegerField(help_text='sub_view_count', null=True)),
            ],
        ),
    ]
