# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_index_count',
            field=models.IntegerField(default=0, help_text='page_index_count', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='sub_view_count',
            field=models.IntegerField(default=0, help_text='sub_view_count', null=True),
        ),
    ]
